/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeemains;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author gaurav
 */
public class AnsDataBaseCreater extends javax.swing.JFrame {

    public static String TABLE_NAME = "ANSRECORD";
    public static String COL_QUES_NO = "QUESNO";
    public static String COL_ANS = "ANS";
    
    /**
     * Creates new form AnsDataBaseCreater
     */
    public AnsDataBaseCreater() {
        initComponents();
        
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        qno = new javax.swing.JTextField();
        qans = new javax.swing.JTextField();
        qsub = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        qno.setText("1");
        qno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qnoActionPerformed(evt);
            }
        });

        qans.setText("1");
        qans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qansActionPerformed(evt);
            }
        });

        qsub.setText("PHYSICS");

        jButton2.setText("drop tables");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(qno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qans, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(qsub, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qans, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qsub, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insertIntoDatabase();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qansActionPerformed
        // TODO add your handling code here:
        insertIntoDatabase();
        qans.setText("");
    }//GEN-LAST:event_qansActionPerformed

    public void insertIntoDatabase(){
        createTable();
        int no =Integer.parseInt(qno.getText());
        int ans =Integer.parseInt(qans.getText());
        String sub=qsub.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            String sql = "INSERT INTO "+TABLE_NAME+sub+" VALUES (" +no+" ,"
                    +ans+" );"; 
            s.executeUpdate(sql);
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println("--"+e);
        }
        
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM "+TABLE_NAME+sub+ " WHERE "+COL_QUES_NO +" = "+no+" ;";
            //System.out.println(""+sql);
            ResultSet rs=s.executeQuery(sql);
            rs.next();
            
            System.out.println(""+rs.getInt(COL_ANS));
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        
        if(no<30){
            qno.setText(""+(no+1));
        }else{
            qno.setText(""+1);
        }
    }
    
    private void qnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qnoActionPerformed
        // TODO add your handling code here:
        qans.requestFocus();
    }//GEN-LAST:event_qnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String sub = qsub.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            String sql1 = "DROP TABLE "+TABLE_NAME+"PHYSICS ;";
            String sql2 = "DROP TABLE "+TABLE_NAME+"CHEMISTRY ;";
            String sql3 = "DROP TABLE "+TABLE_NAME+"MATHS ;";
            s.executeUpdate(sql1);
            s.executeQuery(sql2);
            s.executeQuery(sql3);
            c.close();
            s.close();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void createTable(){
        String sub = qsub.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            String sql = "CREATE TABLE "+TABLE_NAME+sub+"("+COL_QUES_NO+" int PRIMARY KEY,"
                    + ""+COL_ANS+" int "
                    + ");";
            s.executeUpdate(sql);
            c.close();
            s.close();
            
        }catch(Exception e){
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnsDataBaseCreater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnsDataBaseCreater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnsDataBaseCreater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnsDataBaseCreater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnsDataBaseCreater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField qans;
    private javax.swing.JTextField qno;
    private javax.swing.JTextField qsub;
    // End of variables declaration//GEN-END:variables
}
