/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeemains;

import java.awt.Button;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JButton;
import static jeemains.AnsDataBaseCreater.TABLE_NAME;

/**
 *
 * @author gaurav
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
        b1.requestFocus();
        int i=0;
        
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            int x= 3 * 60 * 60 ;
            String sql1 = "CREATE TABLE TIMMEER (" + TestFrame.COL_TIMER + " int "
                    + ");";
            String sql2 = "INSERT INTO TIMMEER VALUES (" + x + " );";
            
            s.executeUpdate(sql1);
            
            s.executeQuery(sql2);
            
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        
        
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            String sql1 = "DROP TABLE ANSP ;";
            
            s.executeUpdate(sql1);
            
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            
            String sql2 = "DROP TABLE ANSC ;";
           
           
            s.executeUpdate(sql2);
            
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            
            String sql3 = "DROP TABLE ANSM ;";
            
            
            s.executeUpdate(sql3);
           
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            
            String sql4 = "DROP TABLE GUESSP ;";
           
            
            s.executeUpdate(sql4);
        
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
            
            String sql5 = "DROP TABLE GUESSC ;";
         
            
            s.executeUpdate(sql5);
       
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();
            
           
            String sql6 = "DROP TABLE GUESSM ;";
            
            s.executeUpdate(sql6);
            
            c.close();
            s.close();
            
        }catch(Exception e){
            System.out.println(""+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JLabel();
        inputNameTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        b1.setText("Name :");

        inputNameTextField.setFont(new java.awt.Font("Garamond", 2, 18)); // NOI18N
        inputNameTextField.setForeground(new java.awt.Color(0, 102, 51));
        inputNameTextField.setText("Enter your name");
        inputNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNameTextFieldFocusGained(evt);
            }
        });

        jButton1.setText("Start Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b.setText("bbb");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(b)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputNameTextField)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameTextFieldFocusGained
        // TODO add your handling code here:
        inputNameTextField.setText(null);
    }//GEN-LAST:event_inputNameTextFieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = inputNameTextField.getText();
        new TestFrame(name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    
    
    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JLabel b1;
    private javax.swing.JTextField inputNameTextField;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
