/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeemains;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static jeemains.AnsDataBaseCreater.COL_ANS;
import static jeemains.AnsDataBaseCreater.COL_QUES_NO;
import static jeemains.AnsDataBaseCreater.TABLE_NAME;

/**
 *
 * @author gaurav
 */
public class TestFrame extends javax.swing.JFrame {

    public static final String COL_TIMER = "TIMMEEERR";
    int timmeer = 2 * 60 * 60;

    enum Subject {

        P, C, M
    };
    Subject sub;
    int index;
    int questionsAttemptedNo = 0, questionsGuessedNo = 0;

    int questionNo;

    CurrentSubject currentSubject[] = new CurrentSubject[3];

    /**
     * Creates new form TestFrame
     */
    public TestFrame(String name) {
        initComponents();
        initialise();
        currentSubject[0] = new CurrentSubject(Subject.P);
        currentSubject[1] = new CurrentSubject(Subject.C);
        currentSubject[2] = new CurrentSubject(Subject.M);
        refreshButtonColors();

        testRadio.setVisible(false);
        new timmer();
    }

    public void initialise() {
        createTables();
        sub = Subject.P;
        physicsButton.setEnabled(false);
        questionNo = 1;
        index = 0;
        loadQuestion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        timerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mathsButton = new javax.swing.JButton();
        chemistryButton = new javax.swing.JButton();
        physicsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        questionButton1 = new javax.swing.JButton();
        questionButton2 = new javax.swing.JButton();
        questionButton3 = new javax.swing.JButton();
        questionButton4 = new javax.swing.JButton();
        questionButton5 = new javax.swing.JButton();
        questionButton6 = new javax.swing.JButton();
        questionButton7 = new javax.swing.JButton();
        questionButton8 = new javax.swing.JButton();
        questionButton9 = new javax.swing.JButton();
        questionButton10 = new javax.swing.JButton();
        questionButton11 = new javax.swing.JButton();
        questionButton12 = new javax.swing.JButton();
        questionButton13 = new javax.swing.JButton();
        questionButton14 = new javax.swing.JButton();
        questionButton15 = new javax.swing.JButton();
        questionButton16 = new javax.swing.JButton();
        questionButton17 = new javax.swing.JButton();
        questionButton18 = new javax.swing.JButton();
        questionButton19 = new javax.swing.JButton();
        questionButton20 = new javax.swing.JButton();
        questionButton21 = new javax.swing.JButton();
        questionButton22 = new javax.swing.JButton();
        questionButton23 = new javax.swing.JButton();
        questionButton24 = new javax.swing.JButton();
        questionButton25 = new javax.swing.JButton();
        questionButton26 = new javax.swing.JButton();
        questionButton27 = new javax.swing.JButton();
        questionButton28 = new javax.swing.JButton();
        questionButton29 = new javax.swing.JButton();
        questionButton30 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        questionNoLabel = new javax.swing.JLabel();
        questionImageLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        optionSelected1 = new javax.swing.JRadioButton();
        optionSelected2 = new javax.swing.JRadioButton();
        optionSelected3 = new javax.swing.JRadioButton();
        optionSelected4 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        leaveAndMoveToNextButton = new javax.swing.JButton();
        guessButton = new javax.swing.JButton();
        saveAndContinueButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        questionsAttemptedLabel = new javax.swing.JLabel();
        questionsGuessedLabel = new javax.swing.JLabel();
        testRadio = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timerButton.setText("timer");
        timerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mathsButton.setText("Maths");
        mathsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsButtonActionPerformed(evt);
            }
        });

        chemistryButton.setText("Chemistry");
        chemistryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryButtonActionPerformed(evt);
            }
        });

        physicsButton.setText("Physics");
        physicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsButtonActionPerformed(evt);
            }
        });

        questionButton1.setText("1");
        questionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton1ActionPerformed(evt);
            }
        });

        questionButton2.setText("2");
        questionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton2ActionPerformed(evt);
            }
        });

        questionButton3.setText("3");
        questionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton3ActionPerformed(evt);
            }
        });

        questionButton4.setText("4");
        questionButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton4ActionPerformed(evt);
            }
        });

        questionButton5.setText("5");
        questionButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton5ActionPerformed(evt);
            }
        });

        questionButton6.setText("6");
        questionButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton6ActionPerformed(evt);
            }
        });

        questionButton7.setText("7");
        questionButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton7ActionPerformed(evt);
            }
        });

        questionButton8.setText("8");
        questionButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton8ActionPerformed(evt);
            }
        });

        questionButton9.setText("9");
        questionButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton9ActionPerformed(evt);
            }
        });

        questionButton10.setText("10");
        questionButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton10ActionPerformed(evt);
            }
        });

        questionButton11.setText("11");
        questionButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton11ActionPerformed(evt);
            }
        });

        questionButton12.setText("12");
        questionButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton12ActionPerformed(evt);
            }
        });

        questionButton13.setText("13");
        questionButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton13ActionPerformed(evt);
            }
        });

        questionButton14.setText("14");
        questionButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton14ActionPerformed(evt);
            }
        });

        questionButton15.setText("15");
        questionButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton15ActionPerformed(evt);
            }
        });

        questionButton16.setText("16");
        questionButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton16ActionPerformed(evt);
            }
        });

        questionButton17.setText("17");
        questionButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton17ActionPerformed(evt);
            }
        });

        questionButton18.setText("18");
        questionButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton18ActionPerformed(evt);
            }
        });

        questionButton19.setText("19");
        questionButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton19ActionPerformed(evt);
            }
        });

        questionButton20.setText("20");
        questionButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton20ActionPerformed(evt);
            }
        });

        questionButton21.setText("21");
        questionButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton21ActionPerformed(evt);
            }
        });

        questionButton22.setText("22");
        questionButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton22ActionPerformed(evt);
            }
        });

        questionButton23.setText("23");
        questionButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton23ActionPerformed(evt);
            }
        });

        questionButton24.setText("24");
        questionButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton24ActionPerformed(evt);
            }
        });

        questionButton25.setText("25");
        questionButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton25ActionPerformed(evt);
            }
        });

        questionButton26.setText("26");
        questionButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton26ActionPerformed(evt);
            }
        });

        questionButton27.setText("27");
        questionButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton27ActionPerformed(evt);
            }
        });

        questionButton28.setText("28");
        questionButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton28ActionPerformed(evt);
            }
        });

        questionButton29.setText("29");
        questionButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton29ActionPerformed(evt);
            }
        });

        questionButton30.setText("30");
        questionButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButton30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(questionButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(questionButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(questionButton15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(questionButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(questionButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(questionButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(questionButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(questionButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(questionButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionButton30)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(physicsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chemistryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mathsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicsButton)
                    .addComponent(mathsButton)
                    .addComponent(chemistryButton))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(timerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(timerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Question", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(153, 102, 255))); // NOI18N

        questionNoLabel.setText("Q.1");

        questionImageLabel.setBackground(new java.awt.Color(153, 204, 255));
        questionImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(questionNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(questionNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        radioButtonGroup.add(optionSelected1);
        optionSelected1.setText("A");

        radioButtonGroup.add(optionSelected2);
        optionSelected2.setText("B");

        radioButtonGroup.add(optionSelected3);
        optionSelected3.setText("C");

        radioButtonGroup.add(optionSelected4);
        optionSelected4.setText("D");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionSelected3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionSelected4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionSelected1)
                    .addComponent(optionSelected2)
                    .addComponent(optionSelected3)
                    .addComponent(optionSelected4))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        leaveAndMoveToNextButton.setText("Leave Empty");
        leaveAndMoveToNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveAndMoveToNextButtonActionPerformed(evt);
            }
        });

        guessButton.setText("Guess(review for later)");
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        saveAndContinueButton.setText("Save & Continue");
        saveAndContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(leaveAndMoveToNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveAndContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveAndContinueButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(leaveAndMoveToNextButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guessButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        prevButton.setText("prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText("next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prevButton))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Questions for Review");

        jLabel4.setText("Questions Attempted");

        questionsAttemptedLabel.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N

        questionsGuessedLabel.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(questionsGuessedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionsAttemptedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionsGuessedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(questionsAttemptedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radioButtonGroup.add(testRadio);
        testRadio.setText("jRadioButton1");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(testRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton9ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(9);
    }//GEN-LAST:event_questionButton9ActionPerformed

    private void questionButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton7ActionPerformed
        randomAcessButtonClicked(7);        // TODO add your handling code here:
    }//GEN-LAST:event_questionButton7ActionPerformed

    private void questionButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton4ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(4);
    }//GEN-LAST:event_questionButton4ActionPerformed

    private void questionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton2ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(2);
    }//GEN-LAST:event_questionButton2ActionPerformed

    int count = 0;
    private void timerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerButtonActionPerformed

        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("hi");
        if (input.equals("!t@ch!@")) {

            String in = JOptionPane.showInputDialog("hi");
           
                try {
                        
                        int x = Integer.parseInt(in);
                        t.sleep(x*1000);
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(TestFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            

        }
    }//GEN-LAST:event_timerButtonActionPerformed

    private void leaveAndMoveToNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveAndMoveToNextButtonActionPerformed
        // TODO add your handling code here:
        int ans = 0;

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "INSERT INTO GUESS" + sub + " VALUES (" + questionNo + " ,"
                    + ans + " );";
            String sql2 = "INSERT INTO ANS" + sub + " VALUES (" + questionNo + " ,"
                    + ans + " );";
             
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "UPDATE GUESS" + sub + " SET " + COL_ANS + " = " + ans + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            String sql2 = "UPDATE ANS" + sub + " SET " + COL_ANS + " = " + ans + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            System.out.println("" + sql1);
            s.executeUpdate(sql1);
            s.executeUpdate(sql2);
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("-->>" + e);
        }

        if (currentSubject[index].question[questionNo - 1].state == Question.State.answered) {
            questionsAttemptedNo -= 1;

        } else if (currentSubject[index].question[questionNo - 1].state == Question.State.guessed) {
            questionsGuessedNo -= 1;
        }

        currentSubject[index].question[questionNo - 1].state = Question.State.seen;

        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_leaveAndMoveToNextButtonActionPerformed

    private void saveAndContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndContinueButtonActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        int ans = 0;
        if (optionSelected1.isSelected()) {
            ans = 1;
        } else if (optionSelected2.isSelected()) {
            ans = 2;
        } else if (optionSelected3.isSelected()) {
            ans = 3;
        } else if (optionSelected4.isSelected()) {
            ans = 4;
        }
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "INSERT INTO GUESS" + sub + " VALUES (" + questionNo + " ,"
                    + ans + " );";
            String sql2 = "INSERT INTO ANS" + sub + " VALUES (" + questionNo + " ,"
                    + ans + " );";
            s.executeUpdate(sql1);
            s.executeUpdate(sql2);
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "UPDATE GUESS" + sub + " SET " + COL_ANS + " = " + ans + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            String sql2 = "UPDATE ANS" + sub + " SET " + COL_ANS + " = " + ans + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            s.executeUpdate(sql1);
            s.executeUpdate(sql2);
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

        if (ans != 0) {
            if (currentSubject[index].question[questionNo - 1].state == Question.State.guessed) {
                questionsGuessedNo -= 1;
                questionsAttemptedNo += 1;
            } else if (currentSubject[index].question[questionNo - 1].state != Question.State.answered) {
                questionsAttemptedNo += 1;
            }

            currentSubject[index].question[questionNo - 1].state = Question.State.answered;
        } else {
            currentSubject[index].question[questionNo - 1].state = Question.State.seen;
        }
        nextButtonActionPerformed(evt);

        //loadQuestion();

    }//GEN-LAST:event_saveAndContinueButtonActionPerformed

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        int ans = 0;
        if (optionSelected1.isSelected()) {
            ans = 1;
        } else if (optionSelected2.isSelected()) {
            ans = 2;
        } else if (optionSelected3.isSelected()) {
            ans = 3;
        } else if (optionSelected4.isSelected()) {
            ans = 4;
        }
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql = "INSERT INTO GUESS" + sub + " VALUES (" + questionNo + " ,"
                    + ans + " );";
            s.executeUpdate(sql);
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "UPDATE GUESS" + sub + " SET " + COL_ANS + " = " + ans + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            s.executeUpdate(sql1);
            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

        if (ans != 0) {

            if (currentSubject[index].question[questionNo - 1].state == Question.State.answered) {

                try {
                    Class.forName("java.sql.Driver");
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
                    Statement s = c.createStatement();

                    String sql2 = "UPDATE ANS" + sub + " SET " + COL_ANS + " = " + 0 + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
                    s.executeUpdate(sql2);
                    c.close();
                    s.close();

                } catch (Exception e) {
                    System.out.println("-->>" + e);
                }

                questionsGuessedNo += 1;
                questionsAttemptedNo -= 1;
            } else if (currentSubject[index].question[questionNo - 1].state != Question.State.guessed) {
                questionsGuessedNo += 1;
            }

            currentSubject[index].question[questionNo - 1].state = Question.State.guessed;
        } else {
            currentSubject[index].question[questionNo - 1].state = Question.State.seen;
        }

        nextButtonActionPerformed(evt);

        //loadQuestion();

    }//GEN-LAST:event_guessButtonActionPerformed

    public void colorChange() {
        if (currentSubject[index].question[questionNo - 1].state == Question.State.answered) {
            getButtonFromNumber(questionNo).setBackground(Color.GREEN);
        } else if (currentSubject[index].question[questionNo - 1].state == Question.State.guessed) {
            getButtonFromNumber(questionNo).setBackground(Color.YELLOW);
        } else {
            currentSubject[index].question[questionNo - 1].state = Question.State.seen;
            getButtonFromNumber(questionNo).setBackground(Color.RED);
        }
    }

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        //JButton button ;
        //button = getButtonFromNumber(questionNo);
        //button.setEnabled(true);

        colorChange();
        if (questionNo > 1) {
            questionNo--;
        }
        //button = getButtonFromNumber(questionNo);
        //button.setEnabled(false);

        loadQuestion();
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        //JButton button ;
        //button = getButtonFromNumber(questionNo);
        colorChange();
        ///button.setEnabled(true);
        if (questionNo < 30) {
            questionNo++;
        }
        //button = getButtonFromNumber(questionNo);
        //button.setEnabled(false);

        loadQuestion();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void questionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton1ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(1);
    }//GEN-LAST:event_questionButton1ActionPerformed

    private void questionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton3ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(3);
    }//GEN-LAST:event_questionButton3ActionPerformed

    private void questionButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton5ActionPerformed

        randomAcessButtonClicked(5);        // TODO add your handling code here:
    }//GEN-LAST:event_questionButton5ActionPerformed

    private void questionButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton6ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(6);
    }//GEN-LAST:event_questionButton6ActionPerformed

    private void questionButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton8ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(8);
    }//GEN-LAST:event_questionButton8ActionPerformed

    private void questionButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton10ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(10);
    }//GEN-LAST:event_questionButton10ActionPerformed

    private void questionButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton11ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(11);
    }//GEN-LAST:event_questionButton11ActionPerformed

    private void questionButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton12ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(12);
    }//GEN-LAST:event_questionButton12ActionPerformed

    private void questionButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton13ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(13);
    }//GEN-LAST:event_questionButton13ActionPerformed

    private void questionButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton14ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(14);
    }//GEN-LAST:event_questionButton14ActionPerformed

    private void questionButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton15ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(15);
    }//GEN-LAST:event_questionButton15ActionPerformed

    private void questionButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton16ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(16);
    }//GEN-LAST:event_questionButton16ActionPerformed

    private void questionButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton17ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(17);
    }//GEN-LAST:event_questionButton17ActionPerformed

    private void questionButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton18ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(18);
    }//GEN-LAST:event_questionButton18ActionPerformed

    private void questionButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton19ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(19);
    }//GEN-LAST:event_questionButton19ActionPerformed

    private void questionButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton20ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(20);
    }//GEN-LAST:event_questionButton20ActionPerformed

    private void questionButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton21ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(21);
    }//GEN-LAST:event_questionButton21ActionPerformed

    private void questionButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton22ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(22);
    }//GEN-LAST:event_questionButton22ActionPerformed

    private void questionButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton23ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(23);
    }//GEN-LAST:event_questionButton23ActionPerformed

    private void questionButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton24ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(24);
    }//GEN-LAST:event_questionButton24ActionPerformed

    private void questionButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton25ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(25);
    }//GEN-LAST:event_questionButton25ActionPerformed

    private void questionButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton26ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(26);
    }//GEN-LAST:event_questionButton26ActionPerformed

    private void questionButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton27ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(27);
    }//GEN-LAST:event_questionButton27ActionPerformed

    private void questionButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton28ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(28);
    }//GEN-LAST:event_questionButton28ActionPerformed

    private void questionButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton29ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(29);
    }//GEN-LAST:event_questionButton29ActionPerformed

    private void questionButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButton30ActionPerformed
        // TODO add your handling code here:
        randomAcessButtonClicked(30);
    }//GEN-LAST:event_questionButton30ActionPerformed

    private void physicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsButtonActionPerformed
        // TODO add your handling code here:
        sub = Subject.P;
        chemistryButton.setEnabled(true);
        mathsButton.setEnabled(true);
        physicsButton.setEnabled(false);
        refreshButtonColors();
        loadQuestion();


    }//GEN-LAST:event_physicsButtonActionPerformed

    private void chemistryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryButtonActionPerformed
        // TODO add your handling code here:
        sub = Subject.C;
        chemistryButton.setEnabled(false);
        mathsButton.setEnabled(true);
        physicsButton.setEnabled(true);
        refreshButtonColors();
        loadQuestion();
    }//GEN-LAST:event_chemistryButtonActionPerformed

    private void mathsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsButtonActionPerformed
        // TODO add your handling code here:
        sub = Subject.M;
        chemistryButton.setEnabled(true);
        mathsButton.setEnabled(false);
        physicsButton.setEnabled(true);
        refreshButtonColors();
        loadQuestion();
    }//GEN-LAST:event_mathsButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        finishThis();
    }//GEN-LAST:event_submitButtonActionPerformed

    public void randomAcessButtonClicked(int x) {

        //JButton button;
        //button = getButtonFromNumber(questionNo); 
        //button.setEnabled(true);
        colorChange();
        questionNo = x;

        loadQuestion();
        //button= getButtonFromNumber(x);
        //button.setEnabled(false);
    }

    public void createTables() {

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql1 = "CREATE TABLE ANSP(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            String sql2 = "CREATE TABLE ANSC(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            String sql3 = "CREATE TABLE ANSM(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            String sql4 = "CREATE TABLE GUESSP(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            String sql5 = "CREATE TABLE GUESSC(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            String sql6 = "CREATE TABLE GUESSM(" + COL_QUES_NO + " int PRIMARY KEY,"
                    + "" + COL_ANS + " int "
                    + ");";
            s.executeUpdate(sql1);
            s.executeUpdate(sql2);
            s.executeUpdate(sql3);
            s.executeUpdate(sql4);
            s.executeUpdate(sql5);
            s.executeUpdate(sql6);

            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("--" + e);
        }

    }

    Thread t;

    class timmer implements Runnable {

        timmer() {
            t = new Thread(this, "hrithiki");
            t.start();
        }

        @Override
        public void run() {
            try {
                for (; timmeer > 0;) {
                    timmeer--;
                    timerButton.setText("" + timmeer / (60 * 60) + ":" + (timmeer % (60 * 60)) / 60 + ":" + timmeer % 60);
                    //System.out.println(timmeer);
                    Thread.sleep(1000);
                }

                finishThis();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            } catch (InterruptedException ex) {
                Logger.getLogger(TestFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void finishThis() {
        new Results().setVisible(true);
        this.dispose();
    }

    void changeButtonColor(int x, Color c) {
        JButton button = getButtonFromNumber(x + 1);
        button.setBackground(c);
    }

    public void refreshButtonColors() {

        Color color;
        if (sub == Subject.P) {
            index = 0;
        } else if (sub == Subject.C) {
            index = 1;
        } else {
            index = 2;
        }

        for (int i = 0; i < 30; ++i) {
            if (currentSubject[index].question[i].state == Question.State.answered) {
                color = Color.GREEN;
                changeButtonColor(i, color);
            } else if (currentSubject[index].question[i].state == Question.State.guessed) {
                color = Color.YELLOW;
                changeButtonColor(i, color);
            } else if (currentSubject[index].question[i].state == Question.State.seen) {
                color = Color.RED;
                changeButtonColor(i, color);
            } else {
                color = Color.cyan;
                changeButtonColor(i, color);
            }
        }

        questionNo = 1;

    }

    public void loadQuestion() {

        optionSelected1.setSelected(false);
        optionSelected2.setSelected(false);
        optionSelected3.setSelected(false);
        optionSelected4.setSelected(false);
        testRadio.setSelected(true);

        getButtonFromNumber(questionNo).setBackground(Color.blue);

        updateDisplayVariables();

        try {

            Class.forName("java.sql.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement statement = connection.createStatement();

            String sql1 = "SELECT * FROM GUESS" + sub + " WHERE " + COL_QUES_NO + " = " + questionNo + " ;";
            //System.out.println(""+sql);

            ResultSet resultSet = statement.executeQuery(sql1);

            if (resultSet.next()) {
                int tempResult = resultSet.getInt(COL_ANS);

                switch (tempResult) {
                    case 1:
                        optionSelected1.setSelected(true);
                        break;
                    case 2:
                        optionSelected2.setSelected(true);
                        break;
                    case 3:
                        optionSelected3.setSelected(true);
                        break;
                    case 4:
                        optionSelected4.setSelected(true);
                        break;
                    default:
                        testRadio.setSelected(true);
                }
            } else {
                testRadio.setSelected(true);

            }

            connection.close();
            resultSet.close();
            statement.close();
        } catch (Exception e) {

            System.out.println("" + e);
        }

        questionNoLabel.setText("Q. " + questionNo);

        String quesPicName;
        quesPicName = "img" + sub + questionNo;
        //System.out.println(""+quesPicName);
        //quesPicName = "trytry";
        ImageIcon icon = new ImageIcon(getClass().getResource("/QuestionImages/" + quesPicName + ".jpg"));
        Image i = icon.getImage().getScaledInstance(questionImageLabel.getWidth(), questionImageLabel.getHeight(), Image.SCALE_AREA_AVERAGING);

        questionImageLabel.setIcon(new ImageIcon(i));

    }

    public void updateDisplayVariables() {

        questionsAttemptedLabel.setText("" + questionsAttemptedNo);
        questionsGuessedLabel.setText("" + questionsGuessedNo);

    }

    public JButton getButtonFromNumber(int x) {
        switch (x) {
            case 1:
                return questionButton1;
            case 2:
                return questionButton2;
            case 3:
                return questionButton3;
            case 4:
                return questionButton4;
            case 5:
                return questionButton5;
            case 6:
                return questionButton6;
            case 7:
                return questionButton7;
            case 8:
                return questionButton8;
            case 9:
                return questionButton9;
            case 10:
                return questionButton10;
            case 11:
                return questionButton11;
            case 12:
                return questionButton12;
            case 13:
                return questionButton13;
            case 14:
                return questionButton14;
            case 15:
                return questionButton15;
            case 16:
                return questionButton16;
            case 17:
                return questionButton17;
            case 18:
                return questionButton18;
            case 19:
                return questionButton19;
            case 20:
                return questionButton20;
            case 21:
                return questionButton21;
            case 22:
                return questionButton22;
            case 23:
                return questionButton23;
            case 24:
                return questionButton24;
            case 25:
                return questionButton25;
            case 26:
                return questionButton26;
            case 27:
                return questionButton27;
            case 28:
                return questionButton28;
            case 29:
                return questionButton29;
            case 30:
                return questionButton30;

        }
        return new JButton();
    }

    @Override
    public void dispose() {
        super.dispose();

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav", "root", "");
            Statement s = c.createStatement();

            String sql2 = "INSERT INTO TIMMEER VALUES (" + timmeer + " );";

            s.executeQuery(sql2);

            c.close();
            s.close();

        } catch (Exception e) {
            System.out.println("" + e);
        }

        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame("Guest").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chemistryButton;
    private javax.swing.JButton guessButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton leaveAndMoveToNextButton;
    private javax.swing.JButton mathsButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton optionSelected1;
    private javax.swing.JRadioButton optionSelected2;
    private javax.swing.JRadioButton optionSelected3;
    private javax.swing.JRadioButton optionSelected4;
    private javax.swing.JButton physicsButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton questionButton1;
    private javax.swing.JButton questionButton10;
    private javax.swing.JButton questionButton11;
    private javax.swing.JButton questionButton12;
    private javax.swing.JButton questionButton13;
    private javax.swing.JButton questionButton14;
    private javax.swing.JButton questionButton15;
    private javax.swing.JButton questionButton16;
    private javax.swing.JButton questionButton17;
    private javax.swing.JButton questionButton18;
    private javax.swing.JButton questionButton19;
    private javax.swing.JButton questionButton2;
    private javax.swing.JButton questionButton20;
    private javax.swing.JButton questionButton21;
    private javax.swing.JButton questionButton22;
    private javax.swing.JButton questionButton23;
    private javax.swing.JButton questionButton24;
    private javax.swing.JButton questionButton25;
    private javax.swing.JButton questionButton26;
    private javax.swing.JButton questionButton27;
    private javax.swing.JButton questionButton28;
    private javax.swing.JButton questionButton29;
    private javax.swing.JButton questionButton3;
    private javax.swing.JButton questionButton30;
    private javax.swing.JButton questionButton4;
    private javax.swing.JButton questionButton5;
    private javax.swing.JButton questionButton6;
    private javax.swing.JButton questionButton7;
    private javax.swing.JButton questionButton8;
    private javax.swing.JButton questionButton9;
    private javax.swing.JLabel questionImageLabel;
    private javax.swing.JLabel questionNoLabel;
    private javax.swing.JLabel questionsAttemptedLabel;
    private javax.swing.JLabel questionsGuessedLabel;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JButton saveAndContinueButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton testRadio;
    private javax.swing.JButton timerButton;
    // End of variables declaration//GEN-END:variables
}
